Iteration 5
kaa-it/go-devops pull request #6
Opened 2024-03-30 08:51 UTC by kaa-it

2024-03-31 23:13 UTC, avhitrov requested changes
Очень порадовала изначально грамотная организация процессов и забота о многопотоковой защите. Есть несколько замечаний в комментариях к коду. Из них самое весомое - неверная огранизация сохранения счетчика. В остальном все хорошо. Жду исправлений.

2024-03-31 23:13 UTC, avhitrov commented on cmd/agent/README.md
> +| `SERVER_ADDERSS` | Base address for metrics server | `127.0.0.1:8080` |
```suggestion
| `SERVER_ADDRESS` | Base address for metrics server | `127.0.0.1:8080` |
```

2024-03-31 23:13 UTC, avhitrov commented on internal/agent/agent.go
> +	pollTicker := time.NewTicker(a.config.Agent.PollInterval)
```
defer pollTicker.Stop()
```
Хорошим стилем будет останавливать тикеры по завершении работы. Даже в таком вырожденном случае.

2024-03-31 23:13 UTC, avhitrov commented on internal/agent/agent.go
> +	reportTicker := time.NewTicker(a.config.Agent.ReportInterval)
```
defer reportTicker.Stop()
```

2024-03-31 23:13 UTC, avhitrov commented on internal/agent/agent.go
> +		}
После успешной отправки счетчика его необходимо сбрасывать. Значение счетчика на сервере должно отражать реальное количество циклов по сбору данных. И увеличиваться линейно. В настоящей реализации значение счетчика на сервере увеличиваться нелинейно, в сложной геометрической прогрессии.

2024-03-31 23:13 UTC, avhitrov commented on internal/agent/storage.go
> +func (s *Storage) TotalGauges() int {
Точно так, как и в предыдущих функциях, необходимо включать блокировку для безопасного чтения мапы. Примерно так:
```
s.mu.Lock()
defer s.mu.Unlock()
```

https://t.me/bushigo/24

2024-03-31 23:13 UTC, avhitrov commented on internal/server/server.go
> +		log.Println(err)
```suggestion
		log.Fatal(err)
```
Это не слишком важно, но так принято.

2024-03-31 23:13 UTC, avhitrov commented on internal/server/storage/memory/repository.go
> +		s.mu.RUnlock()
Съедаем производительность в угоду красоте. Переключение блокировки - весьма тяжелая процедура и постоянно щелкать этим тумблером в цикле обычно означает сильно тормозить приложение. Я бы предложил пересмотреть псевдоитератор в пользу функции, сразу возвращающей список. Или, как вариант, блокировать один раз перед циклом и разблокировать после. Ну и необходимо держать в голове, что данный набор функций (ForEachGauge, ForEachCounter) можно использовать только для получения данных, для итерации с изменением нужна либо замена на Lock-Unlock (тогда набор будет универсальным), либо еще пара функций с блокировкой на запись. И разделить эти две пары названиями.

Надеюсь, не очень сумбурно получилось.

2024-04-01 11:11 UTC, kaa-it commented on internal/server/storage/memory/repository.go
> +		s.mu.RUnlock()
Поскольку сигнатура передаваемой в качестве параметра функции не подразумевает изменения данных, решил остановиться на втором варианте и вынести блокировки только для чтения перед циклом.

2024-04-01 13:31 UTC, kaa-it commented on internal/server/storage/memory/repository.go
> +		s.mu.RUnlock()
Вынес блокировки перед циклом. Но при этом ведь мы рискуем надолго заблокировать мапу, если переданная функция fn будет выполняться очень долго? И опять же мы теряем возможность работать еще как-то с мапой в функции fn (как в агенте), так как функция fn теперь выполняется под блокировкой. То есть функция становится менее универсальной.

2024-04-02 00:21 UTC, avhitrov commented on internal/server/storage/memory/repository.go
> +		s.mu.RUnlock()
Само собой, необходимо учитывать примерную сложность и трудоемкость передаваемой функции и сопоставлять ее с длительностью блокировки, но заранее рассчитывать на то, что она будет искать ответ на самый главный вопрос вселенной, видимо, не стоит. Всегда есть довольно ограниченный набор действий, который в максимуме на нее ляжет. И его довольно легко предположить.

2024-04-02 00:26 UTC, avhitrov approved these changes
Все замечания исправлены. Прошу не резолвить мои комментарии, я по ним проверяю проведенную работу и резолвлю сам. В остальном все отлично.

2024-04-05 20:55 UTC, merged